### ISSUE TITLE
Log Function need Fix and address function needs to return receiver's address for security and safety reasons

### ISSUE THREAD

**Issue by vigho4u** [cryptapi/php-cryptapi#3]
Here is my fix for Log

        public function check_logs() {
        if (empty($this->coin) || empty($this->callback_url)) return null;
        
        $callback_url = $this->callback_url;
        if (!empty($this->parameters)) {
            $req_parameters = http_build_query($this->parameters);
            $callback_url = "{$this->callback_url}?{$req_parameters}";
        }

        $params = [
            'callback' => $callback_url,
        ];

        $response = CryptAPI::_request($this->coin, 'logs', $params);

        if ($response->status == 'success') {
            return $response;
        }

        return null;
    }

I made a mistake and transferred to wrong address while testing because first request address is unique to $ca_params
So here is my proposal:

        public function get_address() {
        if (empty($this->own_address) || empty($this->coin) || empty($this->callback_url)) return null;

        $callback_url = $this->callback_url;
        if (!empty($this->parameters)) {
            $req_parameters = http_build_query($this->parameters);
            $callback_url = "{$this->callback_url}?{$req_parameters}";
        }

        $ca_params = array_merge([
            'callback' => $callback_url,
            'address' => $this->own_address,
        ], $this->ca_params);

        $response = CryptAPI::_request($this->coin, 'create', $ca_params);
      
        if ($response->status == 'success') {
            $this->payment_address = $response->address_in;
            $address['address_in'] = $response->address_in; //my addition
            $address['address_out'] = $response->address_out; //my addition

            return $address; 
           //address is an array of address_in and address_out so one can confirm that address_out corresponds to the correct wallet to 
            prevent loss of funds
        }

        return null;
    }

**Comment by cryptapi** [comment]
Hello @vigho4u, thank you for your inputs. 

We've pushed the bugfix for `check_logs` and added a validation that the `address_out` from the API matches the `own_address` of the library.

This way it doesn't break backwards compatibility for other users and the library itself checks that the addresses match (or raises an error), you don't need to code it yourself.

Closing this issue.
